name: Laravel CI

on:
  push:
    branches:
      - alif

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: save-satwa
          MYSQL_ROOT_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.10'

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Show MySQL info
        run: |
          echo "MySQL Service Information:"
          echo "Host: ${{ job.services.mysql.host }}"
          echo "Port: ${{ job.services.mysql.port }}"
          echo "Database: ${{ job.services.mysql.MYSQL_DATABASE }}"
          echo "Username: ${{ job.services.mysql.MYSQL_USER }}"

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
